### ISSUE TITLE
Using in scss

### ISSUE THREAD

**Issue by jeremydouglas** [endtwist/kerning.js#17]
How are kerning.js css statements meant to be written in .scss files? I'm getting an error output of invalid scss when I compile. Even with --quiet, the file written is still an error.

**Comment by benjamingeorge** [comment]
I need help with this as well

**Comment by thenoelforte** [comment]
Yep! Also need help with this!

**Comment by sangyoo91** [comment]
I need help with .less files

**Comment by endtwist** [comment]
You'll have to use string interpolation:
```scss
#{"-word-size"}: #{"-word-pairs('this is': 10em)"};
#{"-letter-size"}: 100px 20px 30px;
```
